### ISSUE TITLE
success messages written to stderr

### ISSUE THREAD

**Issue by jorrit** [kevva/logalot#3]
The imagemin utilities (like mozjpeg-bin) use logalot to write a success message when the downloaded binary passes a sanity test after installation. This success message is written to stderr because of the default output stream of Squeak. This success message ends up as an error in my TFS build server (and possibly on other build platforms too) because it checks the stderr for error messages.

Is it possible to use a separate Squeak instance for info/success messages with stream set to `process.stdout`? If this is acceptable I will make a PR for it, if necessary.

**Comment by sindresorhus** [comment]
It's a common misconception that `stderr` is only for errors. Rather, it's an alternative stream. In imagemin `stderr` used so not to interfere with the other output. It's quite common to use `stderr` for logging. TFS should rely on the exit code rather than `stderr`.
